# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
 pull_request_target:
   types:
   - closed
   branches:
    - main

env:
   project_path: 'Library/TasksLibrary.csproj' 
   output_path:  'bin/Release/net5.0/publish/'
   package_id: 'Adeola.TodoListLibrary'
   major_version: 2
   minor_version: 0
   patch_version: 0
   build_number: ${{ github.run_number }}
   company_name: 'Paprika'
   authors: 'Adeola Aderibigbe'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 6.0.x
    - name: add nuget package
      run: dotnet nuget add source --username paprika --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Adexandria/index.json"
    - name: Pack library
      run: dotnet pack ${{env.project_path}} --configuration Release --output ${{env.output_path}} --no-restore -p:PackageId=${{ env.package_id }} -p:PackageVersion=${{ env.major_version }}.${{ env.minor_version }}.${{ env.build_number }} --property:Authors="${{ env.authors }}" --property:Company="${{ env.company_name }}"
    - name: publish nuget
      run:  dotnet nuget push "**\*.nupkg"  --api-key ${{ secrets.PAT }} --source "https://nuget.pkg.github.com/Adexandria/index.json" -SkipDuplicate -Verbosity detailed
