# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 6.0.x
    - name: add nuget package
      run: dotnet nuget add source --username paprika --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Adexandria/index.json"
    - name: Pack library
      run: dotnet pack --configuration Release
    - name: publish nuget
      run:  dotnet nuget push "bin/Release/TasksLibrary.1.0.0.nupkg"  --api-key ${{ secrets.GITHUB_PAT }} --source "github"
