name: Build and Restore PR branches

on:
  pull_request:
    branches: ["master"]

env:
  project_file: 'Library/TasksLibrary.csproj'


jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore project
      run: dotnet restore 
    - name: Build project
      run: dotnet build ${{env.project_file}} --no-restore
    - name: test
      run: dotnet test


